// <auto-generated />
namespace ManyToManyTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddClass2User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddClass2User));
        
        string IMigrationMetadata.Id
        {
            get { return "201608270857241_AddClass2User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
